#!/usr/bin/env node

const decamelize = require('decamelize');
const moment = require('moment');

moment.locale();

const indexTpl = `
`;

const changelogTpl = `## 0.0.1 (${moment().format('ll')})
`;

const packageTpl = pkgName => `{
  "name": "@nofwl/nx-${decamelize(pkgName, '-')}",
  "version": "0.0.1",
  "description": "",
  "main": "lib/index",
  "module": "esm/index.js",
  "types": "esm/index.d.ts",
  "author": "lencx",
  "license": "MIT",
  "homepage": "https://github.com/nofwl/nx#readme",
  "scripts": {
    "build": "yarn build:cjs && yarn build:esm",
    "build:cjs": "tsc --outDir esm --module es2015",
    "build:esm": "tsc",
    "watch": "tsc --watch"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/nofwl/nx.git"
  },
  "keywords": [
    "${pkgName}"
  ],
  "bugs": {
    "url": "https://github.com/nofwl/nx/issues"
  }
}
`;

const readmeTpl = pkgName => `# ${pkgName}
`;

const tsconfigTpl = `{
  "extends": "../../tsconfig.json",
  "include": ["src"],
  "compilerOptions": {
      "outDir": "lib",
      "rootDir": "src"
  }
}
`;

module.exports = pkgName => {
  const pkgBasePath = `./packages/${pkgName}`;
  return [{
    filename: `${pkgBasePath}/src/index.ts`,
    template: indexTpl,
  }, {
    filename: `${pkgBasePath}/README.md`,
    template: readmeTpl(pkgName),
  }, {
    filename: `${pkgBasePath}/CHANGELOG.md`,
    template: changelogTpl,
  }, {
    filename: `${pkgBasePath}/package.json`,
    template: packageTpl(pkgName),
  }, {
    filename: `${pkgBasePath}/tsconfig.json`,
    template: tsconfigTpl,
  }]
}
